name: meditation_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.5
  characters: ^1.0.0
  equatable: ^1.2.5
  cupertino_icons: ^0.1.3
  firebase_database: ^3.1.1
  firebase_auth: ^0.15.4
  splashscreen : 1.2.0
  flutter_signin_button: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
