name: meditation_app
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^6.0.5
  equatable: ^1.2.5
  cloud_firestore: ^0.14.0+2
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.0.1+1
  characters: ^1.0.0
  cupertino_icons: ^0.1.3
  splashscreen : 1.2.0
  flutter_signin_button: ^1.0.0
  meta: ^1.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/